[prune]
go-tests = true
non-go = true
unused-packages = true


[[constraint]]
name = "github.com/golang/glog"
branch = "master"

[[constraint]]
name = "k8s.io/api"
version = "v0.21.0"

[[override]]
name = "k8s.io/apimachinery"
version = "v0.21.0"

[[constraint]]
name = "k8s.io/client-go"
version = "v0.21.0"

[[override]]
name = "sigs.k8s.io/structured-merge-diff"
version = "v4.1.0"

[[override]]
name = "k8s.io/klog"
version = "v2.8.0"
